config/routes.rb
Pong::Application.routes.draw do
  resources :matches do
    collection do
      get 'rankings'
    end
  end
  root to: 'matches#rankings'
end

app/models/match.rb
class Match < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  include MatchesHelper

  def create
    match = Match.new(params[:match])
    match.save
    redirect_to matches_path
  end

  def index
    @match = Match.new
    @matches = Match.all
  end

  def new
    @match = Match.new
  end

  def rankings
    matches = Match.order("date")
    @rankings = calculate_rankings(matches)
  end

  def update
    match = Match.find_by_id(params[:id])
    match.update_attributes(params[:match])
    redirect_to matches_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
  def calculate_rankings(matches)
    ranking = []

    matches.each do |match|
      winner = match.winner
      loser  = match.loser

      ranking << winner unless ranking.include? winner
      ranking << loser  unless ranking.include? loser

      winner_index = ranking.index(winner)
      loser_index  = ranking.index(loser)

      if winner_index > loser_index
        new_index = (winner_index + loser_index) / 2
        ranking.delete_at(winner_index)
        ranking.insert(new_index, winner)
      end
    end

    ranking
  end
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Pong
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag

  %body
    %h1 Pivot Pong
    #content
      = yield

app/views/matches/index.html.haml
%h2 Match History

%ol
  - @matches.each do |m|
    %li
      .winner= m.winner
      .loser=  m.loser
      %date=   m.date.to_s

= form_for(@match) do |f|
  = f.label :winner
  = f.text_field :winner
  = f.label :loser
  = f.text_field :loser
  = f.label :date
  = f.text_field :date, value: Time.now.strftime("%Y-%m-%d")
  = submit_tag "Add match"

= link_to "Rankings", rankings_matches_path

app/views/matches/rankings.html.haml
- @rankings.each do |player|
  = player


= link_to "Match history", matches_path